version: "3"

services:
  calendar_service:
    build: ./
    command: ./wait-for-postgres.sh postgres ./calendar_service
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    environment:
      DB_PASSWORD: qwer
      

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: calendardb
      POSTGRES_PASSWORD: qwer


  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}]
    volumes:
      - ~/.container-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.container-data/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      
volumes:
  container-data:
